# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test_again.py
# Created on: 2018-05-02 15:32:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

import arcpy


# Local variables:
Subdivisions_Res = "Subdivisions_Res"
subdiv_copy = "C:\\Users\\avenneman\\Documents\\Programming\\SelectWork\\output.gdb\\subdiv_copy"
# Subdivisions_Res_CopyFeature__2_ = subdiv_copy
# subdiv_copy__2_ = subdiv_copy

# Process: Copy Features
arcpy.CopyFeatures_management(Subdivisions_Res, subdiv_copy, "", "0", "0", "0")

# Process: Add Field
arcpy.AddField_management(subdiv_copy, "PRS_COPY", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(subdiv_copy, "PSN_COPY", "!PROJECT_SERIAL_NUMBER!", "PYTHON", "")
